// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fortunex_buff.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ilruntime.Protobuf;
using pbc = global::Google.ilruntime.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace DragonU3DSDK.Network.API.ILProtocol {

  #region Messages
  public sealed class BuffLevelUpBurst : pb::IMessage {
    private static readonly pb::MessageParser<BuffLevelUpBurst> _parser = new pb::MessageParser<BuffLevelUpBurst>(() => new BuffLevelUpBurst());
    public static pb::MessageParser<BuffLevelUpBurst> Parser { get { return _parser; } }

    private ulong timestampLeft_;
    public ulong TimestampLeft {
      get { return timestampLeft_; }
      set {
        timestampLeft_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TimestampLeft != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TimestampLeft);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (TimestampLeft != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimestampLeft);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TimestampLeft = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed class BuffSuperWheel : pb::IMessage {
    private static readonly pb::MessageParser<BuffSuperWheel> _parser = new pb::MessageParser<BuffSuperWheel>(() => new BuffSuperWheel());
    public static pb::MessageParser<BuffSuperWheel> Parser { get { return _parser; } }

    private ulong timestampLeft_;
    public ulong TimestampLeft {
      get { return timestampLeft_; }
      set {
        timestampLeft_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TimestampLeft != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TimestampLeft);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (TimestampLeft != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimestampLeft);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TimestampLeft = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed class BuffDoubleExp : pb::IMessage {
    private static readonly pb::MessageParser<BuffDoubleExp> _parser = new pb::MessageParser<BuffDoubleExp>(() => new BuffDoubleExp());
    public static pb::MessageParser<BuffDoubleExp> Parser { get { return _parser; } }

    private ulong timestampLeft_;
    public ulong TimestampLeft {
      get { return timestampLeft_; }
      set {
        timestampLeft_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TimestampLeft != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TimestampLeft);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (TimestampLeft != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimestampLeft);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TimestampLeft = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed class BuffSeasonQuestStarBoost : pb::IMessage {
    private static readonly pb::MessageParser<BuffSeasonQuestStarBoost> _parser = new pb::MessageParser<BuffSeasonQuestStarBoost>(() => new BuffSeasonQuestStarBoost());
    public static pb::MessageParser<BuffSeasonQuestStarBoost> Parser { get { return _parser; } }

    private ulong timestampLeft_;
    public ulong TimestampLeft {
      get { return timestampLeft_; }
      set {
        timestampLeft_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TimestampLeft != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TimestampLeft);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (TimestampLeft != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimestampLeft);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TimestampLeft = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed class BuffNewbieQuestBoost : pb::IMessage {
    private static readonly pb::MessageParser<BuffNewbieQuestBoost> _parser = new pb::MessageParser<BuffNewbieQuestBoost>(() => new BuffNewbieQuestBoost());
    public static pb::MessageParser<BuffNewbieQuestBoost> Parser { get { return _parser; } }

    private ulong timestampLeft_;
    public ulong TimestampLeft {
      get { return timestampLeft_; }
      set {
        timestampLeft_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TimestampLeft != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(TimestampLeft);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (TimestampLeft != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimestampLeft);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TimestampLeft = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed class CGetBuff : pb::IMessage {
    private static readonly pb::MessageParser<CGetBuff> _parser = new pb::MessageParser<CGetBuff>(() => new CGetBuff());
    public static pb::MessageParser<CGetBuff> Parser { get { return _parser; } }

    public void WriteTo(pb::CodedOutputStream output) {
    }

    public int CalculateSize() {
      int size = 0;
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed class SGetBuff : pb::IMessage {
    private static readonly pb::MessageParser<SGetBuff> _parser = new pb::MessageParser<SGetBuff>(() => new SGetBuff());
    public static pb::MessageParser<SGetBuff> Parser { get { return _parser; } }

    private static readonly pb::FieldCodec<global::DragonU3DSDK.Network.API.ILProtocol.AnyStruct> _repeated_buffs_codec
        = pb::FieldCodec.ForMessage(10, global::DragonU3DSDK.Network.API.ILProtocol.AnyStruct.Parser);
    private readonly pbc::RepeatedField<global::DragonU3DSDK.Network.API.ILProtocol.AnyStruct> buffs_ = new pbc::RepeatedField<global::DragonU3DSDK.Network.API.ILProtocol.AnyStruct>();
    /// <summary>
    /// buff
    /// </summary>
    public pbc::RepeatedField<global::DragonU3DSDK.Network.API.ILProtocol.AnyStruct> Buffs {
      get { return buffs_; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      buffs_.WriteTo(output, _repeated_buffs_codec);
    }

    public int CalculateSize() {
      int size = 0;
      size += buffs_.CalculateSize(_repeated_buffs_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            buffs_.AddEntriesFrom(input, _repeated_buffs_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
