// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fortunex_bankrupt.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ilruntime.Protobuf;
using pbc = global::Google.ilruntime.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace DragonU3DSDK.Network.API.ILProtocol {

  #region Messages
  public sealed class CBankrupt : pb::IMessage {
    private static readonly pb::MessageParser<CBankrupt> _parser = new pb::MessageParser<CBankrupt>(() => new CBankrupt());
    public static pb::MessageParser<CBankrupt> Parser { get { return _parser; } }

    public void WriteTo(pb::CodedOutputStream output) {
    }

    public int CalculateSize() {
      int size = 0;
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed class SBankrupt : pb::IMessage {
    private static readonly pb::MessageParser<SBankrupt> _parser = new pb::MessageParser<SBankrupt>(() => new SBankrupt());
    public static pb::MessageParser<SBankrupt> Parser { get { return _parser; } }

    private bool available_;
    /// <summary>
    /// 是否可以领
    /// </summary>
    public bool Available {
      get { return available_; }
      set {
        available_ = value;
      }
    }

    private uint timestampLeft_;
    /// <summary>
    /// 不能领的原因之一: 时间没到
    /// </summary>
    public uint TimestampLeft {
      get { return timestampLeft_; }
      set {
        timestampLeft_ = value;
      }
    }

    private bool tooMuchCoins_;
    /// <summary>
    /// 不能领的原因之二: 还没破产
    /// </summary>
    public bool TooMuchCoins {
      get { return tooMuchCoins_; }
      set {
        tooMuchCoins_ = value;
      }
    }

    private global::DragonU3DSDK.Network.API.ILProtocol.UserProfile userProfile_;
    /// <summary>
    /// 领完救济之后的用户数据
    /// </summary>
    public global::DragonU3DSDK.Network.API.ILProtocol.UserProfile UserProfile {
      get { return userProfile_; }
      set {
        userProfile_ = value;
      }
    }

    private ulong coins_;
    /// <summary>
    /// 领取的钱
    /// </summary>
    public ulong Coins {
      get { return coins_; }
      set {
        coins_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Available != false) {
        output.WriteRawTag(8);
        output.WriteBool(Available);
      }
      if (TimestampLeft != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(TimestampLeft);
      }
      if (TooMuchCoins != false) {
        output.WriteRawTag(24);
        output.WriteBool(TooMuchCoins);
      }
      if (userProfile_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(UserProfile);
      }
      if (Coins != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(Coins);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Available != false) {
        size += 1 + 1;
      }
      if (TimestampLeft != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TimestampLeft);
      }
      if (TooMuchCoins != false) {
        size += 1 + 1;
      }
      if (userProfile_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserProfile);
      }
      if (Coins != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Coins);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Available = input.ReadBool();
            break;
          }
          case 16: {
            TimestampLeft = input.ReadUInt32();
            break;
          }
          case 24: {
            TooMuchCoins = input.ReadBool();
            break;
          }
          case 34: {
            if (userProfile_ == null) {
              userProfile_ = new global::DragonU3DSDK.Network.API.ILProtocol.UserProfile();
            }
            input.ReadMessage(userProfile_);
            break;
          }
          case 40: {
            Coins = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
